name: IE Tests

on:
  - workflow_dispatch
  - push
  - pull_request

jobs:
  local-tests:
    name: Local Tests
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 3.0, 3.2 ]
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v2
      - name: Set Windows resolution
        run: Set-DisplayResolution -Width 1920 -Height 1080 -Force
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install gems
        run: bundle install
      - name: Run tests
        run: bundle exec rake spec:ie
        env:
          GITHUB_TOKEN: ${{ github.token }}
