name: Safari Tests

on:
  - workflow_dispatch
  - push
  - pull_request

jobs:
  local-tests:
    name: Local Tests
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 3.0, 3.2 ]
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v2
      - name: Set Mac resolution
        run: |
          system_profiler SPDisplaysDataType | grep Resolution
          "/Library/Application Support/VMware Tools/vmware-resolutionSet" 2560 1440
          system_profiler SPDisplaysDataType | grep Resolution
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install gems
        run: bundle install
      - name: Configure safaridriver
        run: |
          defaults write com.apple.Safari IncludeDevelopMenu YES
          defaults write com.apple.Safari AllowRemoteAutomation 1
          sudo safaridriver --enable
          safaridriver --version
          safaridriver -p 0 &
      - name: Run tests
        run: bundle exec rake spec:safari
