name: Unit Tests

on:
  - workflow_dispatch
  - push
  - pull_request

jobs:
  documentation-test:
    name: Yard Doctest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v2
      - name: Setup Fluxbox
        run: sudo apt-get -y install fluxbox
      - name: Start XVFB
        run: Xvfb :99 -screen 0 1920x1280x24 > /dev/null 2>&1 &
      - name: Start Fluxbox
        run: fluxbox -display :99 &
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: Install gems
        run: bundle install
      - name: Run tests
        run: bundle exec rake yard:doctest

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.0', '3.1', '3.2', 'jruby-9.4.0.0', 'truffleruby-22.3.0']
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v2
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install gems
        run: bundle install
      - run: bundle exec rake spec:unit

  linter-test:
    name: Rubocop Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v2
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: Install gems
        run: bundle install
      - run: bundle exec rubocop
